name: Get latest rental prices from Peartree

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '15,45 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with: 
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager py-cord pandas
    - name: Fetch latest data
      run: |
        python fetch_data_peartree.py
    - name: Check for changes and send message
      env: 
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        python check_and_update_peartree.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
